### ISSUE TITLE
[QUESTION] Where is stub.apk coming from

### ISSUE THREAD

**Issue by PeterNjeim** [Dr-TSNG/ApplistDetector#19]
Where is the stub.apk file coming from? I've been trying to bypass your Magisk Manager detection but I haven't been able to. I looked in the MAGISKTMP folder and there's no stub.apk there, and I looked through all the code of the app but I can't see how the stub.apk file is generated or retrieved.

Thanks in advance

**Comment by Dr-TSNG** [comment]
https://github.com/topjohnwu/Magisk/releases/download/v25.2/stub-release.apk

**Comment by PeterNjeim** [comment]
So that file is bundled with the ApplistDetector app?

**Comment by PeterNjeim** [comment]
That's really smart. I honestly don't know of a way to bypass your method, wondering if you know of any way to do so

**Comment by PeterNjeim** [comment]
What I'm thinking is to do something similar like GameGuardian or LuckyPatcher, where you download an installer, which then installs the real app. The installer can generate the app in a slightly random way so that the values that you check are slightly different for everyone (I understand that your size detection has a range though, so that's the only one that won't be randomized). Or maybe the "hide the magisk manager" button itself can do this randomization.

What do you think?

**Comment by Dr-TSNG** [comment]
> That's really smart. I honestly don't know of a way to bypass your method, wondering if you know of any way to do so

It can be easily bypassed by inserting dummy activities/services/permissions to the stub. Anyway you should modify some Magisk source code to make it work correctly since adding dummy components may break the stub loading logic.
https://github.com/topjohnwu/Magisk/blob/52ba6d11bca116008d8df0c53ffa4942f4f5dc5c/stub/src/main/java/com/topjohnwu/magisk/ClassLoaders.java#L37
